spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/book_manager?characterEncording=utf8
    username: root
    password: mysql
    driverClassaname: com.mysql.jdbc.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE